name: simbox_workspace_probe
load_stage:
  scene_loader:
    type: env_loader
    args:
      workflow_type: SimBoxDualWorkFlow
      cfg_path: workflows/simbox/core/configs/tasks/example/sort_the_rubbish.yaml
      simulator:
        physics_dt: 1/30
        rendering_dt: 1/30
        stage_units_in_meters: 1.0
        headless: true
        anti_aliasing: 0
        active_gpu: 0
        physics_gpu: 0
        cuda_device: 0
        multi_gpu: false
        max_gpu_count: 1
  layout_random_generator:
    type: env_randomizer
    args:
      random_num: 1
      strict_mode: true
plan_with_render_stage:
  plan_with_render:
    type: plan_with_render
    args:
      save_failed: false
store_stage:
  writer:
    type: env_writer
    args:
      batch_async: false
      output_dir: null
      seq_output_dir: output/.workspace_probe_unused
