nav2_skill:
  planner_server:
    plugin: nav2_navfn_planner/NavfnPlanner
  controller_server:
    min_y_velocity_threshold: 0.0
  costmap:
    footprint_padding: 0.02
    inflation_layer:
      cost_scaling_factor: 2.0
  velocity_smoother:
    feedback: OPEN_LOOP
